### ISSUE TITLE
Tags not working when add it to github.io

### ISSUE THREAD

**Issue by nina-weng** [yak-fumblepack/jekyll-academic#1]
When I build the website based on github.io, everything works perfectly but the tag part failed. Do you have any ideas why it happened and how to solove that?

**Comment by m1kql** [comment]
Github has a whitelist for certain plugins, so custom plugins like this one that creates tags for the posts will do nothing. Github does this for security issues; however, there's a workaround for this too.

If you want to use github pages to deploy, there's this action which would probably help with your issue conveniently.

> 🪂 A Github Action to deploy the Jekyll site conveniently for GitHub Pages. 
> https://github.com/jeffreytse/jekyll-deploy-action

Otherwise, there are other hosting providers such as [netlify](https://www.netlify.com/). There's a fantastic list of hosting providers compiled by [jekyllthemes.io here](https://jekyllthemes.io/resources/jekyll-hosting-and-cms-solutions) as well.

I hope this helps with the issue. I'll work on a fix so that tags work in github pages natively. Thanks for bringing it to my attention!
